<a href="https://colab.research.google.com/github/chanakyavasantha/ML_Algorithms/blob/main/LearnTensorFlow/LearnTf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# initialzation of tensors
x = tf.constant(4)
print(x)
y = tf.constant(4,shape = (1,1), dtype = tf.float32)
print(y)
z = tf.ones((3,3))
print(z)
w = tf.zeros((2,3))
print(w)
a = tf.random.normal((3,3),mean = 0, stddev=1)
print(a)
b = tf.random.uniform((1,3),minval = 0,maxval = 1)
print(b)
c = tf.range(start = 1,limit = 10, delta = 2)
print(c)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.79880685  1.5896864  -0.33045202]
 [-1.7538661  -0.940934   -1.4052567 ]
 [-0.48841637 -0.8434778  -0.72920024]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.3687209  0.12658632 0.65064085]], shape=(1, 3), dtype=float32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
# casting tensors
x = tf.cast(x, dtype = tf.float16)
print(x)

tf.Tensor(4.0, shape=(), dtype=float16)


In [ ]:
# mathematical Operations on tensors
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
print(z)
# or z = x + y

# similiarly we can perform subtraction , multiplication, division

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
# we can do matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)


tf.Tensor(
[[ 0.29081     2.1970232   5.370161   -1.400056  ]
 [ 0.31100243  0.7083168   0.90736175  0.1811533 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.29081     2.1970232   5.370161   -1.400056  ]
 [ 0.31100243  0.7083168   0.90736175  0.1811533 ]], shape=(2, 4), dtype=float32)


In [ ]:
# indexing a tensor
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
indices = tf.constant([0,2])
x_ind = tf.gather(x,indices)
print(x_ind)
x = tf.constant([[1,2],
                [3,4]])
print(x[0:2,:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# keras and functional api
from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)


In [ ]:
# flatten x_train to train neural network
x_train = x_train.reshape(-1, 28*28).astype("float32")/255.0
x_test = x_test.reshape(-1, 28*28).astype("float32")/255.0

In [ ]:
from keras.engine.training import optimizer
# sequential one to one output
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential(
    [
        keras.Input(shape = (28*28)),
        layers.Dense(512,activation = 'relu'),
        layers.Dense(256, activation = 'relu'),
        layers.Dense(10),
    ]
)

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics = )
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits =True),
    optimizer = keras.optimizers.Adam(lr = 0.001),
    metrics = ["accuracy"],
)
model.fit(x_train, y_train, batch_size = 32, epochs=5,verbose = 2)
model.evaluate(x_test, y_test, batch_size = 32, verbose = 2)



Epoch 1/5
1875/1875 - 17s - loss: 0.1860 - accuracy: 0.9433 - 17s/epoch - 9ms/step
Epoch 2/5
1875/1875 - 16s - loss: 0.0813 - accuracy: 0.9747 - 16s/epoch - 9ms/step
Epoch 3/5
1875/1875 - 17s - loss: 0.0550 - accuracy: 0.9826 - 17s/epoch - 9ms/step
Epoch 4/5
1875/1875 - 16s - loss: 0.0418 - accuracy: 0.9863 - 16s/epoch - 8ms/step
Epoch 5/5
1875/1875 - 19s - loss: 0.0325 - accuracy: 0.9895 - 19s/epoch - 10ms/step
313/313 - 1s - loss: 0.0778 - accuracy: 0.9782 - 962ms/epoch - 3ms/step


[0.07780319452285767, 0.9782000184059143]

In [ ]:
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 512)               401920    
                                                                 
 dense_9 (Dense)             (None, 256)               131328    
                                                                 
 dense_10 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# Functional API is more flexible
inputs = keras.Input(shape = (28*28))
x = layers.Dense(512, activation = 'relu')(inputs)
x = layers.Dense(256, activation = 'relu')(x)
outputs = layers.Dense(10, activation = 'softmax')(x)
model = keras.Model(inputs = inputs , outputs = outputs)
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits =True),
    optimizer = keras.optimizers.Adam(lr = 0.001),
    metrics = ["accuracy"],
)
model.fit(x_train, y_train, batch_size = 32, epochs=5,verbose = 2)
model.evaluate(x_test, y_test, batch_size = 32, verbose = 2)


Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 - 18s - loss: 0.1862 - accuracy: 0.9426 - 18s/epoch - 10ms/step
Epoch 2/5
1875/1875 - 17s - loss: 0.0815 - accuracy: 0.9749 - 17s/epoch - 9ms/step
Epoch 3/5
1875/1875 - 17s - loss: 0.0555 - accuracy: 0.9824 - 17s/epoch - 9ms/step
Epoch 4/5
1875/1875 - 17s - loss: 0.0428 - accuracy: 0.9861 - 17s/epoch - 9ms/step
Epoch 5/5
1875/1875 - 16s - loss: 0.0328 - accuracy: 0.9894 - 16s/epoch - 9ms/step
313/313 - 1s - loss: 0.0831 - accuracy: 0.9770 - 1s/epoch - 5ms/step


[0.08309361338615417, 0.9769999980926514]

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 784)]             0         
                                                                 
 dense_17 (Dense)            (None, 512)               401920    
                                                                 
 dense_18 (Dense)            (None, 256)               131328    
                                                                 
 dense_19 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [ ]:
pred = model.predict(x_train)
print(*pred[0] , end = " ")

1875/1875 [==============================] - 7s 4ms/step
1.3877073e-20 1.490865e-11 1.9312456e-14 0.0011821645 1.30787926e-20 0.99881786 2.5669162e-18 1.1780943e-15 1.8641824e-13 2.079765e-09 

In [ ]:
ans = pred[0][0]
ansIndex = 0
for i in range(len(pred[0])):
  if pred[0][i] > ans:
    ans = pred[0][i]
    ansIndex = i
print(ansIndex)
print("There fore the output cell represents the probabilites of each class")

5
There fore the output cell represents the probabilites of each class


In [ ]:
# implementing other optimizers
# sgd with momentum, adagrad, RMSprop

In [ ]:
# observing difference on removing normalization of data